version: '3.1'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/data=/var/lib/mysql
        
  app:
    container_name: camille
    volumes:
      - .env:/.env
    build: .